# -*- mode: ruby -*-
# vi: set ft=ruby :
#
hostname   = "sparkleshare"
boxname    = "SparkleShare"
private_ip_address = "192.168.50.10"

box_url    = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

Vagrant.configure(2) do |config|

  config.vm.define "#{boxname}" do |master|

  master.vm.box      = "#{boxname}"
  master.vm.hostname = "#{hostname}"
  master.vm.box_url  = "#{box_url}"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "#{private_ip_address}"

  config.vm.provider "virtualbox" do |vb|
    vb.name = master.vm.hostname.to_s
    vb.cpus   = 2
    vb.memory = 1024
  end

# libwebkit2gtk-3.0 \
# libwebkit2gtk-3.0-dev \
# sparkleshare \

  config.vm.provision "shell", name: "sparkleshare-install", privileged: true,
  inline: <<-SHELL
   sudo add-apt-repository -y ppa:meebey/mono-preview
   sudo add-apt-repository -y ppa:rebuntu16/sparkleshare+unofficial
   apt-get update -yq
   apt-get install -y \
       desktop-file-utils \
       git \
       git-core \
       gtk-sharp3 \
       intltool \
       libdbus-glib1.0-cil-dev \
       libsoup2.4-cil-dev \
       libtool \
       libwebkitgtk-3.0-dev \
       mono-devel \
       mono-gmcs \
       mono-mcs \
       monodevelop \
       nant \
       wget
   wget -q -O - https://download.gnome.org/sources/notify-sharp/3.0/notify-sharp-3.0.3.tar.xz | tar xfJ -
   cd notify-sharp-* && ./configure && make && make install && cd .. && rm -rf notify-sharp-*
   git clone https://github.com/stsundermann/webkitgtk-sharp.git
   cd webkitgtk-sharp* && ./autogen.sh && ./configure && make && make install && cd .. && rm -rf webkitgtk-sharp*
   git clone https://github.com/hbons/SparkleShare.git
   cd SparkleShare && ./autogen.sh && ./configure && make && make install
  SHELL
end

  config.vm.provision "shell", name: "sparkleshare-service", 
  privileged: true, run: "always", inline: <<-SHELL
  sparkleshare start
  SHELL

  # Sparkleshare for dummies.
  # http://wwwf.imperial.ac.uk/~buzzard/sparkleshare_for_dummies.html
end
